version: '3.1'

services:

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: expresso
        volumes: 
            - phmongo:/data/db       
        ports:
            - "27017:27017"
#        deploy:
#            replicas: 1
#            placement:
#                constraints: [node.labels.server==serv2]
#            restart_policy:
#                condition: on-failure    
        networks:
            - mongo-net

    servicepod:
        image: adityariyadi/servicepod:latest
        environment:
            PARK_LOCATION: TEST_LOC
            HOST: https://restapi.spotima.id
        ports:
            - "8189:8189"
        networks:
            - mongo-net
        depends_on:
            - mongodb

volumes:
    phmongo:

networks:
    mongo-net: